Resources:
    TaskDefinitionYelbGateway:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: yelb-gateway
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
            TaskRoleArn: !Ref YelbECSTaskIamRole
            ExecutionRoleArn: !Ref 'YelbECSTaskExecutionRole'
            Cpu: 256
            Memory: 512
            ContainerDefinitions:
                - Name: envoy
                  PortMappings:
                    - ContainerPort: 80
                  Image: 840364872350.dkr.ecr.us-east-2.amazonaws.com/aws-appmesh-envoy:v1.12.3.0-prod
                  Essential: true
                  Ulimits:
                      - Name: nofile
                        HardLimit: 15000
                        SoftLimit: 15000
                  HealthCheck:
                      Command:
                          - CMD-SHELL
                          - curl -s http://localhost:9901/server_info | grep state | grep -q LIVE
                      Interval: 5
                      Timeout: 10
                      Retries: 10
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-group: !Ref AWS::StackName
                          awslogs-region: !Ref AWS::Region
                          awslogs-stream-prefix: yelb-gateway
                  Environment:
                      - Name: ENVOY_LOG_LEVEL
                        Value: debug
                      - Name: ENABLE_ENVOY_STATS_TAGS
                        Value: '1'
                      - Name: ENABLE_ENVOY_DOG_STATSD
                        Value: '1'
                      - Name: STATSD_PORT
                        Value: '8125'
                      - Name: APPMESH_VIRTUAL_NODE_NAME
                        Value:
                            Fn::Join:
                                - ''
                                -
                                    - mesh/
                                    - yelb
                                    - /virtualGateway/
                                    - 'yelb-gateway'
                                    
    YelbECSTaskIamRole:
        Type: AWS::IAM::Role
        Properties:
            Path: /
            AssumeRolePolicyDocument: |
                {
                    "Statement": [{
                        "Effect": "Allow",
                        "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                        "Action": [ "sts:AssumeRole" ]
                    }]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/CloudWatchFullAccess
                - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
                - arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess

    YelbECSTaskExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                - Effect: Allow
                  Principal:
                     Service: [ecs-tasks.amazonaws.com]
                  Action: ['sts:AssumeRole']
            Path: /
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
                - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess